contact_links:
  - name: Discussions
    url: https://github.com/CCBR/CCBR_NextflowTemplate/discussions # TODO replace CCBR_NextflowTemplate in this link with RENEE_NF_ALEC
    about: Please ask and answer questions here.
