## FastQ Screen config 2 — vector and rRNA screen (Biowulf)
## Databases: UniVec vectors, rRNA


DATABASE  Uni_Vec  /data/CCBR_Pipeliner/db/PipeDB/lib/fastq_screen_db/UniVec_vectors/UniVec_vectors
DATABASE  rRNA     /data/CCBR_Pipeliner/db/PipeDB/lib/fastq_screen_db/rRNA/rRNA
