## FastQ Screen config 1 — multi-organism contamination screen (Biowulf)
## Databases: human (hg19), mouse (mm9), bacteria, fungi, virus

THREADS    24

DATABASE  Human     /data/CCBR_Pipeliner/db/PipeDB/lib/fastq_screen_db/hg19/hg19
DATABASE  Mouse     /data/CCBR_Pipeliner/db/PipeDB/lib/fastq_screen_db/mm9/mm9
DATABASE  Bacteria  /data/CCBR_Pipeliner/db/PipeDB/lib/fastq_screen_db/Bacteria/bacteria
DATABASE  Fungi     /data/CCBR_Pipeliner/db/PipeDB/lib/fastq_screen_db/Fungi/fungi
DATABASE  Virus     /data/CCBR_Pipeliner/db/PipeDB/lib/fastq_screen_db/Virus/virus
