## FastQ Screen config 1 — multi-organism contamination screen (FRCE)
## Databases: human (hg19), mouse (mm9), bacteria, fungi, virus


DATABASE  Human     /mnt/projects/CCBR-Pipelines/db/fastq_screen_db/hg19/hg19
DATABASE  Mouse     /mnt/projects/CCBR-Pipelines/db/fastq_screen_db/mm9/mm9
DATABASE  Bacteria  /mnt/projects/CCBR-Pipelines/db/fastq_screen_db/Bacteria/bacteria
DATABASE  Fungi     /mnt/projects/CCBR-Pipelines/db/fastq_screen_db/Fungi/fungi
DATABASE  Virus     /mnt/projects/CCBR-Pipelines/db/fastq_screen_db/Virus/virus
