## FastQ Screen config 2 — vector and rRNA screen (FRCE)
## Databases: UniVec vectors, rRNA


DATABASE  Uni_Vec  /mnt/projects/CCBR-Pipelines/db/fastq_screen_db/UniVec_vectors/UniVec_vectors
DATABASE  rRNA     /mnt/projects/CCBR-Pipelines/db/fastq_screen_db/rRNA/rRNA
